### ISSUE TITLE
[Bug] Inconsistent naming, e.g. `runtime_uuid` & `instance_id`

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh/zenoh-flow#123] opened 2022-09-26 09:47 UTC
### Describe the bug

Consistent naming is preferable. Considering the fact that all unique ids are, in fact, UUID, having `*_uuid` seems the better option.

### To reproduce

N/A

### System info

N/A

**Comment by gabrik** [comment] 2022-10-31 14:46
Duplicate of #119

**Closed by gabrik** 2022-10-31 14:46 UTC
Labels: bug
